### ISSUE TITLE
Add support for "long press" and standardise how actions make use of various inputs.

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/gamepad-navigator#22] opened 2020-07-13 09:18 UTC
Right now we have a bunch of approaches with at least some code duplicated between them to handle various types of input.  Once you've got the core functionality on board in some form (performing an action using at least one type of input), we should review and refactor and make each "style" of interaction into a clearer pattern and ensure that all functions can be used with:

1. Short presses that trigger an action on button release.
2. Long presses that trigger an action on button release after a configured time period.
2. Long presses that repeatedly trigger an action.

We'll need a kind of matrix for these, where you support each type of action for digital buttons, analogue buttons, and axes. This is probably one to handle later, for example, after you've got the configuration panel working.  It may be that we'll want to refactor to have single actions that support a direction and flags for the type of input, so that you don't have quite so many invokers or functions, but we can review closer to time and discuss.

**Comment by the-t-in-rtf** [comment] 2020-07-14 12:17
We should also think about how/whether we can support "chording" where a combination of buttons triggers an action rather than a single input.  For example, one key might act as a "reverse" modifier and change a button press from moving forward to moving backward.

**Comment by duhrer** [comment] 2022-04-05 09:03
I ran into related issues when working on #84.  Because we only track the button press, we can't do things like "hold to repeat", which makes navigation things like an on-screen keyboard pretty tedious.

Our current approach also makes it difficult to provide feedback when a button is held versus when it's released.   To address this (and make chording possible), we would need to:

1. Listen for button down, toggling the state of the button.
2. Periodically refire the event if the button is held.  The repeat rate should be configurable by the user, to avoid retriggering if someone needs more time to release a button.
3. Listen for button up (or infer button up on our state check).
4. For things like "click", we would need to trigger "mousedown", then "click" on button down, and "mouseup"  on release.

In rudimentary testing, I've confirmed that simulated mouse events other than click work:

```
var element = document.querySelector(".osk-key-Space");
elements.dispatchEvent(new MouseEvent("mouseup"));
```

This works in Firefox, Chrome, and Safari.

**Comment by duhrer** [comment] 2022-04-07 08:11
As far as I can see, this is a blocker for #77, and would really help with #84 and #85.

**Comment by duhrer** [comment] 2022-04-07 13:35
It would be good to look at the polling mechanism for the sticks and scrolling.

**Comment by duhrer** [comment] 2023-12-25 11:21
In the work leading up to the upcoming 1.0 release, I ended up refactoring a lot of the things I commented on above, notably the polling between repeats (see #108).

I would consider this issue largely satisfied, and will close it out for now.  I have had other thoughts on supporting "key combos", but I think that's out of scope for this issue (I will write it up separately).

**Closed by duhrer** 2023-12-25 11:21 UTC
Labels: enhancement
